"use client";

import { useEffect, useState } from "react";

interface TocItem {
    id: string;
    text: string;
    level: number;
}

export function TableOfContents() {
    const [headings, setHeadings] = useState<TocItem[]>([]);
    const [activeId, setActiveId] = useState<string>("");

    // Extract headings from the rendered article
    useEffect(() => {
        const article = document.querySelector(".prose");
        if (!article) return;

        const elements = article.querySelectorAll("h2, h3");
        const items: TocItem[] = Array.from(elements)
            .filter((el) => el.id) // Only headings with IDs (generated by your backend)
            .map((el) => ({
                id: el.id,
                text: el.textContent || "",
                level: el.tagName === "H2" ? 2 : 3,
            }));

        setHeadings(items);
    }, []);

    // Track active section on scroll
    useEffect(() => {
        if (headings.length === 0) return;

        const observer = new IntersectionObserver(
            (entries) => {
                // Find the first heading that's visible
                const visible = entries
                    .filter((entry) => entry.isIntersecting)
                    .sort(
                        (a, b) =>
                            a.boundingClientRect.top - b.boundingClientRect.top
                    );

                if (visible.length > 0) {
                    setActiveId(visible[0].target.id);
                }
            },
            {
                rootMargin: "-80px 0px -70% 0px",
                threshold: 0,
            }
        );

        headings.forEach(({ id }) => {
            const el = document.getElementById(id);
            if (el) observer.observe(el);
        });

        return () => observer.disconnect();
    }, [headings]);

    if (headings.length === 0) return null;

    return (
        <nav className="toc">
            <p
                className="m-0 mb-3"
                style={{
                    fontSize: "11px",
                    letterSpacing: "0.08em",
                    textTransform: "uppercase",
                    color: "var(--color-neutral-500)",
                    fontWeight: 600,
                }}
            >
                On this page
            </p>

            <ul className="list-none m-0 p-0">
                {headings.map((heading) => {
                    const isActive = heading.id === activeId;
                    return (
                        <li key={heading.id} className="m-0 p-0">
                            <a
                                href={`#${heading.id}`}
                                className="toc-link block no-underline py-1.5 transition-colors"
                                style={{
                                    paddingLeft: heading.level === 3 ? "16px" : "12px",
                                    borderLeft: `2px solid ${isActive ? "var(--color-accent)" : "transparent"
                                        }`,
                                    fontSize: "13px",
                                    lineHeight: "1.5",
                                    color: isActive
                                        ? "var(--color-accent)"
                                        : "var(--color-neutral-500)",
                                    fontWeight: isActive ? 600 : 400,
                                }}
                            >
                                {heading.text}
                            </a>
                        </li>
                    );
                })}
            </ul>
        </nav>
    );
}
